[project]
name="MUD"
description="Multi User Dungeon"
dynamic=["version"]
readme="README.md"
license = {text = "MIT-0"}
authors = [
 {name = "Artyom Osipchuk (aka artos)", email = "artos4002@yandex.ru"}
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
Appbase="mood"

[tool.setuptools.package-data]
AppBase=["locales/*/*/*.mo"]
