[project]
name="MUD"
description="Multi User Dungeon"
dynamic=["version"]
readme="README.md"
license = "MIT"
authors = [
 {name = "Artyom Osipchuk (aka artos)", email = "artos4002@yandex.ru"}
]
scripts = {mud = "MUD:mud"}

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
MUD="mood"

[tool.setuptools.package-data]
MUD=["locales/*/*/*.mo"]

#[dependencies]
#["python-cowsay"]
